---
workspace:
  base: /go
  path: src/github.com/nytimes/vault-fastly-secret-engine

pipeline:
  mod-download:
    image: golang:1
    commands:
      - go mod download
    when:
      event: [push, tag]

  test:
    image: golang:1
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go test ./...
    when:
      event: push

  build:
    image: golang:1
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - mkdir upload
      - make build
      - mv vault-fastly-secret-engine upload/
      - shasum -a 256 upload/vault-fastly-secret-engine | cut -d " " -f1 > upload/SHA256SUMS.txt
    when:
      branch: master
      event: push

  publish:
    image: plugins/gcs
    source: upload/
    target: vault-fastly-secret-engine/latest/
    acl: allUsers:READER
    # nytimes/vault-datadog-secret-engine/secret/drone-google-credential
    secrets: [google_credentials]
    when:
      branch: master
      event: push

  publish-release:
    image: plugins/gcs
    source: upload/
    target: "vault-fastly-secret-engine/${DRONE_TAG}/"
    acl: allUsers:READER
    # nytimes/vault-datadog-secret-engine/secret/drone-google-credential
    secrets: [google_credentials]
    when:
      branch: master
      event: tag
