---
workspace:
  base: /go
  path: src/github.com/nytm/vault-fastly-secret-engine

pipeline:

  test:
    image: golang:1.9-alpine
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - apk add --no-cache bash curl git make unzip
      - go get
      - cd plugin/
      - go test
    when:
      branch: master
      event: push

  build:
    image: golang:1.9-alpine
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    commands:
      - go build
    when:
      branch: master
      event: push